### ISSUE TITLE
Error on usage

### ISSUE THREAD

**Issue by mknittig** [AlexanderArvidsson/connect-arango#1]
First of all: Thanks for this lib! Came around just in time.
I configured the connect extension like you described in your README, but I'm getting an exception when I run my node project:

``` /home/mak/git/myproject/node_modules/arangojs/node_modules/micropromise/node_modules/microtask/index.js:54
        } else throw err;
                     ^
TypeError: Cannot read property 'index' of undefined
  at Object.<anonymous> (/home/mak/git/myproject/node_modules/connect-arango/lib/connect-arango.js:107:19)
  at /home/mak/git/myproject/node_modules/connect-arango/lib/database_helper.js:156:34
  at traverse (/home/mak/git/myproject/node_modules/arangojs/node_modules/micropromise/index.js:761:25)
  at drain (/home/mak/git/myproject/node_modules/arangojs/node_modules/micropromise/node_modules/microtask/index.js:50:12)
  at process._tickCallback (node.js:442:13)
```

**Comment by AlexanderArvidsson** [comment]
This could be because the database does not exist?
Have you tried going to ArangoDB Web UI and creating the database?

**Comment by mknittig** [comment]
No, the database does exist. I'm using it successfully with my project..
